check if p4 object is a file
salesforce/p4-fusion pull request #19
Opened 2022-03-04 17:30 UTC by EricAtORS

I tried using p4-fusion on our code base and it was crashing due to associated jobs.

2022-03-07 05:34 UTC, twarit-waikar commented
@EricAtORS Hello! Thank you for sending this PR.

I actually didn't know that `p4 describe` can return results where the `depotFile` key doesn't exist. Can you share some information on in what cases is the `depotFile` key empty?

Based on that we should be able to decide on if that kind of object is worth handling differently or if we can just ignore it.

2022-03-16 13:56 UTC, EricAtORS commented
@twarit-waikar 
I haven't had a chance to login to my linux box with the soruce code and the log files, but it's related to Perforce Jobs.

Essentially, we have our Perforce server integrated with Jira and FishEye.
When JIRA creates a new issue in our of projects, it triggers FishEye to generate an associated job. Then, we can tag our changelists with a job id and JIRA/FishEye will update the issue with the associated changelists that we can see from FishEye.

In our case, `varList` was information about that associated job and not any file in our changelist.

2022-03-16 14:03 UTC, EricAtORS commented
Also, I'm having issues signing the cla.
I had sent an email to `contactoss-cla@salesforce.com` but I just noticed that the email bounced.

2022-03-16 16:20 UTC, twarit-waikar requested changes
Thanks a lot for sending this PR! This was something we didn't realise that could happen.

2022-03-16 16:20 UTC, twarit-waikar commented on p4-fusion/commands/describe_result.cc
> +		// quick exit if the object returned is not a file
```suggestion
		// Quick exit if the object returned is not a file
```
Minor nitpick :)

2022-03-16 16:20 UTC, twarit-waikar commented on p4-fusion/commands/describe_result.cc
> +	if(depotFile == nullptr){
```suggestion
	if(!depotFile)
	{
```
We have been using this style throughout the project, probably should also follow it here

2022-03-16 20:06 UTC, justinharringa commented
> Also, I'm having issues signing the cla. I had sent an email to `contactoss-cla@salesforce.com` but I just noticed that the email bounced.

hey there - have you clicked on the link? Could you help me understand what the issue was? For example, did you click the link? Did you get an error?

Thanks and hope all is well

2022-03-21 06:59 UTC, twarit-waikar commented
Hey @EricAtORS, could you check again if you can sign the CLA?

2022-03-21 14:43 UTC, twarit-waikar commented
@EricAtORS That should be enough then, I will re-trigger the CLA check on this PR. If you may, you can see my suggestions above, most of them are stylistic differences however

2022-03-21 14:45 UTC, twarit-waikar commented
CLA check is completed now. Would like to know if you commit the suggested changes of if I have permission to build on top of your changes so I can make those minor stylistic changes.

Thanks!

2022-03-21 16:37 UTC, EricAtORS commented
@twarit-waikar 
Thanks for updating the checks.

You are more than welcome to build on top of my changes to make the stylistic ones. I just haven't had access to my linux bot to do it. If you do it, it would be very appreciated from my part as I'm not sure when I will get access to my linux box.

2022-03-21 18:38 UTC, twarit-waikar commented
Thanks for sending the PR!

2022-03-21 18:38 UTC, merged