feat(p4_api): support older perforce servers
salesforce/p4-fusion pull request #71
Opened 2024-01-05 09:55 UTC by ppavacic

This change allows use of this software with older perforce servers and clients which don't support "-r" option.
See https://github.com/salesforce/p4-fusion/issues/52 for more.

2024-01-05 10:32 UTC, twaritwaikar requested changes
Thanks for sending this! I think you also need to sign the CLA to finally merge this in. 

However I had a few comments on the PR which are really just stylistic changes, if you don't mind.

2024-01-05 10:32 UTC, twaritwaikar commented on p4-fusion/commands/changes_result.h
> +	void reverse() {
The definition of this function could be shifted to the .cc file since we are really only keep getters/setters at max inside of headers

2024-01-05 10:32 UTC, twaritwaikar commented on p4-fusion/p4_api.cc
> +	auto changes = Run<ChangesResult>("changes", {
`auto` can be turned to `ChangesResult` here. Makes it easier to review :)

2024-01-05 10:32 UTC, twaritwaikar commented on p4-fusion/p4_api.cc
> +	auto changes = Run<ChangesResult>("changes", {
Same about `auto` here

2024-01-05 10:45 UTC, ppavacic commented
Thanks for the quick reply!

> Thanks for sending this! I think you also need to sign the CLA to finally merge this in.
I did, I guess im watiting now for bot to recognize that. 
> 
> However I had a few comments on the PR which are really just stylistic changes, if you don't mind.
they are solved, i also didnt run clang format so we'll see how it goes.

2024-01-11 11:34 UTC, twarit-waikar commented
@ppavacic Thanks for reminding me, I just ran workflows on this PR. Looks like there are a couple formatting fixes left - https://github.com/salesforce/p4-fusion/actions/runs/7420887077/job/20381786678?pr=71

2024-01-11 11:45 UTC, ppavacic commented
> @ppavacic Thanks for reminding me, I just ran workflows on this PR. Looks like there are a couple formatting fixes left - https://github.com/salesforce/p4-fusion/actions/runs/7420887077/job/20381786678?pr=71

can you try now?

2024-01-11 11:47 UTC, twarit-waikar approved these changes

2024-01-11 11:48 UTC, merged

2024-01-11 11:57 UTC, twarit-waikar commented
Thanks a ton for the work

2024-01-11 11:58 UTC, ppavacic commented
that's only a small change heh

thank you for review and fast merge!