Stream Mapping mode
salesforce/p4-fusion pull request #86
Opened 2024-10-12 14:27 UTC by notdanhan

this allows you to use Stream view mappings as per the request of
https://github.com/salesforce/p4-fusion/issues/83

2024-10-12 14:29 UTC, notdanhan commented
I signed the CLA and the bot crashed?

2024-10-12 14:32 UTC, notdanhan commented on p4-fusion/p4_api.h
> -/*
the clang_format file triggered this noise

2024-10-12 14:32 UTC, notdanhan commented on p4-fusion/utils/arguments.h
> +	std::string GetStreamMappings() const { return GetParameter("--streamMappings"); };
the change in this file

2024-10-18 07:32 UTC, twarit-waikar commented on p4-fusion/main.cc
> +			ERR("MaxChanges and StreamMappings cannot be used together! exiting.");
Is there a specific reason for this? If this is enabled, you wouldn't be able to clone the depot in batches and instead it will always need to be done in a single shot. This could be a problem, but I guess we don't have anyone asking for batches right now except for Sourcegraph

2024-10-18 07:33 UTC, twarit-waikar commented on p4-fusion/main.cc
> +		std::sort(changes.begin(), changes.end());
This is a genius way of sorting CLs coming from different streams. Amazing!

2024-10-18 07:35 UTC, twarit-waikar requested changes
Other than this, some tests for the new STDHelper you added would be great! 

Thanks a lot for working on this feature!

2024-10-18 07:35 UTC, twarit-waikar commented on p4-fusion/main.cc
> +		std::string email = "deleted@user.com";
I don't think we should make any changes to this string. This is very much legacy at this point which we can't break for people already using this string to detect deleted users in the generated Git history.

2024-10-18 15:45 UTC, notdanhan commented on p4-fusion/main.cc
> +			ERR("MaxChanges and StreamMappings cannot be used together! exiting.");
I suppose it'll probably work as-is with the max changes stuff since they're sorted in together, I'll have to add extra logic for pruning the vector of ChangeLists at the end, shouldn't take too long to do.

2025-01-26 00:59 UTC, notdanhan commented on tests/tests.utils.h
clang format file reformatted the entire file again

2025-02-04 11:35 UTC, twarit-waikar commented
Merging this. Thanks!

2025-02-04 11:35 UTC, merged

2025-02-04 14:37 UTC, twarit-waikar reviewed
This needed a minor tweak for the build in #87 but thanks for all this work!